name: Feature request
description: Request a locomotion_ros2 feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Approach
    validations:
      required: true
