FROM ros:jazzy

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
COPY . /ws

RUN source /opt/ros/jazzy/setup.bash && colcon build --symlink-install
